### ISSUE TITLE
Consistency Matters than Discipline

### ISSUE THREAD

**Issue by RDharani123** [RDharanitharan123/Learning-All#3]
- It would be great If you learn to be Not To Give Up on any situation

- Its time to Prove , Not to prove - Prove yourself that you can do anything

     ----------------------------God Mode---------------------------

**Comment by RDharanitharan123** [comment]
Sure I will do it , Thanks for the Motivation

**Comment by RDharanitharan123** [comment]
Hi Bro , Thanks for the suggestion

**Comment by RDharani123** [comment]
No issue Cheers
